[build]
  functions = "netlify/functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/blog"
  status = 302

[[redirects]]
  from = "/blog"
  to = "/.netlify/functions/blog-index"
  status = 200

[[redirects]]
  from = "/blog/:slug"
  to = "/.netlify/functions/blog-post"
  status = 200
